return {
	lualine_icons = {
		mode = "🐹 ",
		modified = "",
		readonly = "（读）",
	},
	todo_icons = {
		FIX = " ",
		TODO = " ",
		HACK = " ",
		WARN = " ",
		PERF = " ",
		NOTE = "󱞁 ",
		-- NOTE = "󱜾 ",
		TEST = " ",
	},
	dap_icons = {
		Stopped = "󰁕 ",
		Breakpoint = " ",
		BreakpointCondition = " ",
		BreakpointRejected = " ",
		LogPoint = ".>",
	},
	diagnostics = {
		Error = " ",
		Warn = " ",
		Hint = " ",
		Info = " ",
	},
	tree_icon = {
		folder_closed = "",
		folder_open = "",
		folder_empty = "",
		folder_empty_open = "",
		-- The next two settings are only a fallback, if you use nvim-web-devicons and configure default icons there
		-- then these will never be used.
		default = "",
	},
	tree_modified = {
		symbol = "",
	},
	git_status = {
		added = " ",
		modified = " ",
		removed = " ",
		deleted = " ", -- this can only be used in the git_status source
		renamed = "󰬙 ", -- this can only be used in the git_status source
		untracked = "󱀶 ",
		ignored = "󱋭 ",
		unstaged = " ",
		staged = "󰄵 ",
		conflict = " ",
	},
	mason_icons = {
		package_installed = "󰝥 ",
		package_pending = "󰴲 ",
		package_uninstalled = "󰝦 ",
	},
	cmp_kinds = {
		Array = " ",
		Boolean = "󰨙 ",
		Class = " ",
		Codeium = "󰘦 ",
		Color = " ",
		Control = " ",
		Collapsed = " ",
		Constant = "󰏿 ",
		Constructor = " ",
		Copilot = " ",
		Enum = " ",
		EnumMember = " ",
		Event = " ",
		Field = " ",
		File = " ",
		Folder = " ",
		Function = "󰊕 ",
		Interface = " ",
		Key = " ",
		Keyword = " ",
		Method = "󰊕 ",
		Module = " ",
		Namespace = "󰦮 ",
		Null = " ",
		Number = "󰎠 ",
		Object = " ",
		Operator = " ",
		Package = " ",
		Property = " ",
		Reference = " ",
		Snippet = " ",
		String = " ",
		Struct = "󰆼 ",
		TabNine = "󰏚 ",
		Text = " ",
		TypeParameter = " ",
		Unit = " ",
		Value = " ",
		Variable = "󰀫 ",
	},
}
